tabNames = cell(1,19);
tabNames{1} = 'Name';
tabNames{2} = 'Date';
tabNames{3} = 'Number_of_Pulses';
tabNames{4} = 'Pulse_Width';
tabNames{5} = 'ISI';
tabNames{6} = 'Electrode_Number';
tabNames{7} = 'Power';
tabNames{8} = 'Cluster';
tabNames{9} = 'Max_Z_Score';
tabNames{10} = 'Binned_PSTH';
tabNames{11} = 'animal_code';
tabNames{12} = 'response_class';
tabNames{13} = 'Multipeak_PSTH';
tabNames{14} = 'NumTrials';
tabNames{15} = 'Energy';
tabNames{16} = 'Stimulation_Time';
tabNames{17} = 'Timeseries_Class';
tabNames{18} = 'BARS_Mean';
tabNames{19} = 'BARS_MAP';
tabNames{20} = 'BARS_Up_Quantile';
tabNames{21} = 'BARS_Low_Quantile';
tabNames{22} = 'BARS_Max_Firing_Rate';
tabNames{23} = 'Where_Bars_Max_Firing';
tabNames{24} = 'Is_Responsive';
tabNames{25} = 'Entropy';
tabNames{26} = 'NSB';

%tabNames{26} = 'BARS_Mean_True';
%tabNames{27} = 'Stand_BARS_Z';
%tabNames{28} = 'Max_BARS_Z';
%load('INS_dataStore.mat');
statTable = cell2table(INSDataTable,'VariableNames',tabNames);
writetable(statTable,'C:\CodeRepos\SpikeAnalysis\INS_statTable_MKV.csv');